def printHelp():
    print("")
    print("Scramble:")
    print("    scramb.py -i <inputfile> [-m <mask.png/.jpg>] -o <outputfile.jpg>  [OPTIONS]")
    print("        You must use -m and/or -s for scramb.py to detect that you want to scramble")
    print("")
    print("Descramble:")
    print("    scramb.py <inputfile.jpg>                        (also usable for drag & drop)")
    print("    scramb.py -i <inputfile.jpg> -o <outputfile.jpg>")
    print("")
    print("Calculate Residue:")
    print("    scramb.py -r <imagefile1.jpg> <imagefile2.jpg>")
    print("")
    print("Options")
    print("    -x <number>   specific parameter for the chosen scrambler")
    print("    -y <number>   specific parameter for the chosen scrambler")
    print("    -z <number>   specific parameter for the chosen scrambler")
    print("    -s <scrambler>")
    print("                  matrix   x=seed y=turn percentage")
    print("                  medium   x=seed y=rounds z=distance")
    print("                  heavy    x=seed y=rounds")
    print("    -2            blowup image by 2x")
    print("    --quality     JPEG Output Quality 0-100, 100=best, default=100")
    print("    --no-logo     do not include Logo in Image")
    print("    -t \"<text>\"   embed text to show when descrambling (max. 400 chars)")
    print("    --silent      do not pause on descramble for displaying text")
    print("    -p            scramble with password (ask for it)")
    print("    --password=<password>")
    print("                  scramble with <password> (caution: it's then in your console history...)")
    print("    --stealth     hide password use from generated image")
    print("                  You must run descrambling with -p or --password option then!")
    print("    --overwrite   Overwrite output file when it exists")
    print("    -d <disguiseimage.jpg>")
    print("                  Enables patch mode with a disguise image for scramble and descramble")
    print("                  When scrambling: This will output a patch image as -o and this -d image")
    print("                           is used as a thumbnail (the disguise image)")
    print("                  When descrambling: This is the disguise image that is patched with")
    print("                           the patch image provided by -i")
